### ISSUE TITLE
RotaryEncoder without velocity

### ISSUE THREAD

**Issue by azerupi** [ostenning/rotary-encoder#1]
Hi thanks for this crate !
I'm using a modified version of this crate for a personal project.
I (currently) don't need the velocity of the encoder and I don't want to deal with getting a datetime from the system clock. So I modified the code to have 2 structs, one with velocity and one without. I think this might interest other people.

Would you be interested in a pull-request?

**Comment by ost-ing** [comment]
Sure thing, send it across :)
