### ISSUE TITLE
more explicit license info?

### ISSUE THREAD

**Issue by x37v** [ostenning/rotary-encoder#3]
I see `MIT` in your Cargo.toml but it might be nice to get that into the README and maybe a copy of the file with copyright info into the repo: https://opensource.org/licenses/MIT

Maybe it doesn't really matter but on github, you end up having to know to look into Cargo.toml to find it..

**Comment by ost-ing** [comment]
Hey, thanks for getting in contact. Sure thing, I'll update the repository shortly with the licensing information.
