### ISSUE TITLE
Version 0.2.0 gives less stable results than 0.1.1

### ISSUE THREAD

**Issue by faern** [ostenning/rotary-encoder#7]
Hi. Thank you for this library! I started using it on ESP32 a few months ago. Just in toy example projects. Today I tried updating the dependency to 0.2.0 but I started getting invalid rotation events and in general less predicable and stable results.

Maybe I'm using the library all wrong or maybe it does not work very cleanly with this microcontroller (ESP32-C3)? I'll link to the code I'm running: https://github.com/faern/iof-rotary-encoder/blob/46180a15b4d0538df726933428cd9ef0ab352307/examples/hello-encoder.rs

This exact code above, but using `rotary-encoder-embedded 0.1.1` works perfectly.

The "noise" I'm seeing includes
* Getting the invalid direction out of the library (tested by just rotating in a single direction but seeing the program print both)
* Sometimes triggering twice on just passing a single dent
* Sometimes not triggering at all on passing a single dent

**Comment by ost-ing** [comment]
Hi @faern , I see that your using GPIO Edge interrupts. I recommend using a Timer, there is an explanation in the readme.
This should yield significantly better results. Let me know how it goes.

Cheers

**Comment by faern** [comment]
Thanks. I'll look into it! Do you have a recommendation on approx how frequently to fire the timer to not miss any pulse from the rotary encoder? It sounds like a pretty dirty solution since the timer will fire constantly even if it's not rotated.

**Comment by ost-ing** [comment]
~950Hz.

My goal for this library is to provide the most accurate and smooth encoder experience, so every indent is detected without fail. I'm using this for a commercial product, so its important that it works very reliably. 
Through my evaluation of opensource solutions as well as experimentation on trying to achieve this, this timer based approach definitely works better than GPIO interrupts.

I suggest you try it out, and if you find performance to be a limiting factor I could also add the state-table method from 0.1.1 back into the project.

**Comment by faern** [comment]
Ok. I trust you know this way better than me. But it feels counter-intuitive that just looking at the GPIO state once every x ticks would be more reliable than having the hardware trigger an interrupt at every edge (should in theory never miss a single indent?)

Thanks for the frequency recommendation. I'll play with this in the weekend and see what I come up with.

Edit: I now see your note about this in https://github.com/ostenning/rotary-encoder-embedded#a-note-about-gpio-or-timer-interrupt-usage. I guess the interrupt noise you talk about for edge triggering could be mitigated with a simple filter circuit as recommended by rotary encoder datasheets?

**Comment by faern** [comment]
I got it working smoothly with timers using `rotary-encoder-embedded 0.2.0` now. I can't really tell if it works better or worse than edge triggered interrupts with `rotary-encoder-embedded 0.1.1`, both works fine. I'll close this issue

https://github.com/faern/iof-rotary-encoder/blob/ef3b090fc6cee01c7528907e74142bfe3c1f9016/examples/hello-encoder.rs
